export const ADD_USER_REQUEST = "ADD_USER_REQUEST"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAILURE = "ADD_USER_FAILURE"

export const SAVE_NOTES_REQUEST = "SAVE_NOTES_REQUEST"
export const SAVE_NOTES_SUCCESS = "SAVE_NOTES_SUCCESS"
export const SAVE_NOTES_FAILURE = "SAVE_NOTES_FAILURE"

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST"
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE"

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION'

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LOG_OUT = 'LOG_OUT'; 

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE'

export const SEND_SMS_REQUEST = 'SEND_SMS_REQUEST'
export const SEND_SMS_SUCCESS = 'SEND_SMS_SUCCESS'
export const SEND_SMS_FAILURE = 'SEND_SMS_FAILURE'

export const INPUT_RANGE_VALUE = 'INPUT_RANGE_VALUE'